nick: helpa
alternate_nick: helpa-bot
channels:
  - "#logga"
  - "#rubyonrails"
  - "#railsbridge"
  - "#spree"
  - "#spree-dev"
  - "#Rubyonrails-offtopic"
  - "#ruby"
  - "#rubysherpas"
owner: "radar"
auto_rejoin: true
database:
  adapter: postgresql
  database: railsbot
